/// Flutter icons PokemonIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PokemonIcons
///      fonts:
///       - asset: fonts/PokemonIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PokemonIcons {
  PokemonIcons._();

  static const _kFontFam = 'PokemonIcons';
  static const String? _kFontPkg = null;

  static const IconData pokeball = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData height = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData weight = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pokemon = IconData(
    0xe807,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
